import OpenAI from "openai";
import { appConfig } from "../Utils/AppConfig";
import { ChatCompletionCreateParamsNonStreaming } from "openai/resources";
import { Prompt } from "../Models/Prompt";

class GptService {

    //OpenAI configuration:
	private openai = new OpenAI ({
        apiKey: appConfig.chatGptApiKey,
        dangerouslyAllowBrowser: true
    });

    //Get GPT completion:
    public async getCompletion(prompt: Prompt): Promise<string> {

        // Data to send:
        const body: ChatCompletionCreateParamsNonStreaming = {
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: prompt.systemContent },
                { role: "user", content: prompt.userContent }
            ]
        };

        //Send request:
        const response = await this.openai.chat.completions.create(body)

        //Return completion:
        const completion = response.choices[0].message.content!;
        return completion;
    }

    // Get MCP result:
    public async getMcpResult(input: string): Promise<string> {

        // Adding instructions to ensure the AI uses HTML and no Markdown:
        const enrichedInput = input + ". " + 
            "Format your response using ONLY pure HTML tags (<h3>, <p>, <ul>, <li>). " +
            "Do not use markdown, asterisks, or backticks. " +
            "If an image URL is available, include it in an <img> tag.";

        const body: OpenAI.Responses.ResponseCreateParams = {
            model: "gpt-4o-mini", 
            tools: [{
                type: "mcp",
                server_label: "SkyVacationsMCP",
                server_description: "Sky Vacations database server exposing vacations, users, and followers data.",
                server_url: appConfig.mcpServerUrl,
                require_approval: "never"
            }],
            input: enrichedInput 
        };

        // Execute query against the MCP-connected LLM:
        const response = await (this.openai as any).responses.create(body);

        // Return the final output text generated by the AI:
        return response.output_text;
    }

}

export const gptService = new GptService();
